language: node_js
node_js:
  - '14.0.0'
jobs:
  include:
    - stage: test
      script: yarn test
after_success:
  - yarn codecov

notifications:
  email:
    recipients:
      - me@silverxu.com
    on_success: always
    on_failure: always
